- name: install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: start mysql server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: install boto3 and botocore
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - boto3
  - botocore

- name: set root password
  ansible.builtin.command: >
    mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ lookup('amazon.aws.aws_ssm', '/roboshop/{{ env }}/mysql_root_pass', region='us-east-1', decrypt=True) }}';"
